"""Verify that METRICS.md covers all QualityMetrics output fields.

METRICS.md is auto-generated by ``ayase modules docs``. This test ensures
every module-written QualityMetrics field appears somewhere in the generated
doc, and every QualityMetrics field is accounted for.
"""

from pathlib import Path

from ayase.models import DatasetStats, QualityMetrics


def _load_metrics_md_fields():
    """Extract metric field headings from generated METRICS.md."""
    metrics_path = Path("METRICS.md")
    if not metrics_path.exists():
        return set()
    text = metrics_path.read_text(encoding="utf-8")
    import re
    return set(re.findall(r"^### `(\w+)`", text, flags=re.MULTILINE))


def test_metrics_table_matches_quality_metrics():
    """Verify METRICS.md references are consistent with QualityMetrics model."""
    fields_in_doc = _load_metrics_md_fields()
    # Provenance fields (metric_backends) are not metrics and are not listed in
    # METRICS.md, so exclude them from the doc-consistency checks below.
    model_fields = set(QualityMetrics.model_fields.keys()) - set(
        QualityMetrics._NON_METRIC_FIELDS
    )
    dataset_fields = set(DatasetStats.model_fields.keys())

    # Every field mentioned in METRICS.md must exist in QualityMetrics
    unknown = fields_in_doc - model_fields - dataset_fields
    # Filter out non-field references (e.g. config keys)
    unknown = {f for f in unknown if not any(
        kw in f for kw in ("threshold", "model", "subsample", "device", "mode")
    )}
    assert not unknown, f"METRICS.md references unknown fields: {unknown}"

    documented_qm_fields = fields_in_doc & model_fields
    missing = model_fields - documented_qm_fields
    assert not missing, f"METRICS.md omits QualityMetrics fields: {missing}"

    # QualityMetrics field count must be correct
    assert len(model_fields) == 436, f"Expected 436 fields, got {len(model_fields)}"
